"""
Report Writer: 把 PER Loop 的输出格式化为结构化 markdown 报告。
"""
from __future__ import annotations

from datetime import datetime


def write_report(
    question: str,
    answer: str,
    context: list[dict],
    iterations: int,
    elapsed: float,
) -> str:
    """生成 markdown 报告字符串（不写文件，由调用方决定存储方式）。"""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# MacroLens Research Report",
        f"",
        f"**Generated**: {now}  ",
        f"**Query**: {question}  ",
        f"**Iterations**: {iterations} | **Time**: {elapsed:.1f}s | **Context items**: {len(context)}",
        f"",
        f"---",
        f"",
        f"## Answer",
        f"",
        answer,
        f"",
        f"---",
        f"",
        f"## Evidence ({len(context)} sources)",
        f"",
    ]

    sec_items = [c for c in context if c["source"] == "sec_chunks"]
    event_items = [c for c in context if c["source"] == "events"]
    macro_items = [c for c in context if c["source"] == "macro_indicators"]

    if sec_items:
        lines += [f"### SEC Filings ({len(sec_items)})", ""]
        for i, c in enumerate(sec_items, 1):
            lines.append(
                f"**[SEC-{i}]** {c.get('doc_type','')} FY{c.get('fiscal_year','')} "
                f"| {c.get('section','')} | {c.get('period_end','')}"
            )
            lines.append(f"> {c['content'][:300].replace(chr(10), ' ')}{'...' if len(c['content']) > 300 else ''}")
            lines.append("")

    if event_items:
        lines += [f"### Events ({len(event_items)})", ""]
        for c in event_items:
            lines.append(f"- **{c['date']}** [{c['category']}] {c['title']}")
        lines.append("")

    if macro_items:
        lines += [f"### Macro Indicators ({len(macro_items)})", ""]
        lines.append("| Series | Date | Value |")
        lines.append("|--------|------|-------|")
        for c in macro_items:
            lines.append(f"| {c['series_id']} | {c['date']} | {c['value']} {c.get('units','')} |")
        lines.append("")

    lines += [
        "---",
        "",
        "*Generated by MacroLens · PER Loop (Plan→Execute→Critique→Synthesize)*",
    ]

    return "\n".join(lines)
